//! The golden fixture harness for the fetch stage.
//!
//! A fixture is a directory under `fixtures/fetch/`, and the directory's name
//! says what the case pins. It holds:
//!
//! - `ticker` — the symbol the case asks about, one line.
//! - `expected` — what the stage must answer, rendered by this file.
//! - one file per recorded response, at the path its URL names:
//!   `www.sec.gov/files/company_tickers.json` is the answer to
//!   `https://www.sec.gov/files/company_tickers.json`.
//!
//! The responses are recordings, taken from EDGAR and committed as they
//! arrived. Nothing here is written by hand, and that is the point: a response
//! composed from memory has the shape somebody remembers rather than the shape
//! the source publishes, and the difference between the two is invisible until
//! it has been believed for a while. To add or refresh a case, ask EDGAR for
//! the URL the file is named after, declaring who you are as its access policy
//! requires, and save the body unchanged:
//!
//! ```text
//! curl -A "you you@example.com" https://www.sec.gov/files/company_tickers.json \
//!     -o fixtures/fetch/<case>/www.sec.gov/files/company_tickers.json
//! ```
//!
//! No case reaches the network. The transport below answers from the case
//! directory and has no wire under it, so a request nothing recorded is a
//! fixture that was never finished — it stops the case and says which file to
//! record, rather than quietly reaching for the real thing.
//!
//! `expected` is never generated by the code it checks: an expected result the
//! subject wrote proves only that the subject agrees with itself. It is written
//! from the recording instead — a history of a thousand filings is read out of
//! the recorded document by something that is not this crate, and what the two
//! readings are being asked is whether they agree.
//!
//! `cargo test` does not select this target (`test = false` in the manifest);
//! `scripts/gates.sh` runs it by name, for the reason the normalize harness
//! gives: the test gate and the fixtures gate have to be able to go red apart.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use vfi_fetch::{
    Cleared, Declaration, Egress, Filing, History, Pace, Response, Retrieved, Ticker, Transport,
    filing_history,
};

/// `fixtures/<stage>/` is this harness's half of `fixtures/`, and it is what
/// scripts/gates.sh reads to decide which harnesses to run. A stage directory
/// with no harness to match is a fixture nobody runs, so the gate goes red
/// there rather than here.
const STAGE: &str = "fetch";

/// The two files a case holds itself, as opposed to the recordings, which sit
/// under a directory named for the host they came from.
const TICKER: &str = "ticker";
const EXPECTED: &str = "expected";

fn stage_fixtures() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures")
        .join(STAGE)
}

/// The directories inside `dir`, in name order: `read_dir` yields whatever
/// order the filesystem holds them in, and a failure list that reorders between
/// two runs of the same tree is one nobody can diff.
///
/// One case is one of these under `fixtures/fetch/`, and one host a case
/// recorded from is one of these under the case.
fn subdirectories(dir: &Path) -> Vec<PathBuf> {
    let entries =
        fs::read_dir(dir).unwrap_or_else(|e| panic!("{}: cannot be read ({e})", dir.display()));

    let mut found: Vec<PathBuf> = entries
        .map(|entry| {
            entry
                .unwrap_or_else(|e| panic!("{}: an entry cannot be read ({e})", dir.display()))
                .path()
        })
        .filter(|path| path.is_dir())
        .collect();

    found.sort();
    found
}

fn read(case: &Path, name: &str) -> String {
    let path = case.join(name);
    fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("{}: a case holds a {name} ({e})", path.display()))
}

/// Every recorded response in a case, keyed by the URL it is the answer to.
///
/// Read up front rather than on demand, so that a recording nothing asks for is
/// visible: a case that stopped following a page would still pass on the
/// records it did read, and the file left unread is the only sign of it.
fn recordings(case: &Path) -> BTreeMap<String, Vec<u8>> {
    let mut recorded = BTreeMap::new();

    for host in subdirectories(case) {
        let name = host
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned();
        collect(&host, &format!("https://{name}"), &mut recorded);
    }

    assert!(
        !recorded.is_empty(),
        "{}: holds no recorded response, so there is nothing for the case to read",
        case.display()
    );
    recorded
}

fn collect(dir: &Path, url: &str, recorded: &mut BTreeMap<String, Vec<u8>>) {
    let entries =
        fs::read_dir(dir).unwrap_or_else(|e| panic!("{}: cannot be read ({e})", dir.display()));

    for entry in entries {
        let path = entry
            .unwrap_or_else(|e| panic!("{}: an entry cannot be read ({e})", dir.display()))
            .path();
        let name = path.file_name().unwrap_or_default().to_string_lossy();
        let url = format!("{url}/{name}");

        if path.is_dir() {
            collect(&path, &url, recorded);
        } else {
            let body = fs::read(&path)
                .unwrap_or_else(|e| panic!("{}: cannot be read ({e})", path.display()));
            recorded.insert(url, body);
        }
    }
}

/// The status a recording is answered with. A case pinning anything else would
/// have to record the status beside the body, and none does: what is pinned
/// here is what the stage makes of a document, and a document is what EDGAR
/// answers 200 with.
const RECORDED_STATUS: u16 = 200;

/// A transport with no wire under it, answering out of one case directory.
struct Recorded {
    case: PathBuf,
    recorded: BTreeMap<String, Vec<u8>>,
    read: Vec<String>,
}

impl Recorded {
    fn of(case: &Path) -> Self {
        Self {
            case: case.to_owned(),
            recorded: recordings(case),
            read: Vec::new(),
        }
    }

    /// Which recordings the case never asked for. A file here is either a
    /// request the stage stopped making or a recording taken for a case that
    /// was then written differently, and both are worth knowing about.
    fn unread(&self) -> Vec<&str> {
        self.recorded
            .keys()
            .filter(|url| !self.read.contains(url))
            .map(String::as_str)
            .collect()
    }
}

impl Transport for Recorded {
    fn send(&mut self, request: Cleared<'_>) -> io::Result<Response> {
        let url = request.url();

        // Not an error the stage is asked to handle. A missing recording is an
        // unfinished fixture, and answering one with a failure would pin the
        // stage's behaviour on a case nobody meant to write.
        let body = self.recorded.get(url).unwrap_or_else(|| {
            panic!(
                "{}: nothing recorded for {url}\n  record it, into {}",
                self.case.display(),
                self.case.join(url.trim_start_matches("https://")).display()
            )
        });

        self.read.push(url.to_owned());
        Ok(Response {
            status: RECORDED_STATUS,
            body: body.clone(),
        })
    }
}

/// Who these cases say is asking. A declaration is the user's to supply, and
/// this is a test standing in for one; the address is `.invalid`, which by
/// RFC 2606 reaches nobody, and nothing here is sent anywhere in any case.
fn declaration() -> Declaration {
    Declaration::new("VFI fixture harness nobody@example.invalid").expect("this names somebody")
}

/// What the stage answered, as text.
///
/// Every record is shown with the request it came from, because that is half of
/// what these cases pin. Sources are written where they change rather than on
/// every line: the records of one request arrive together, so a record filed
/// under the wrong one shows up as a heading in the wrong place.
fn render(ticker: &Ticker, retrieved: &Retrieved, out: &mut String) {
    let _ = writeln!(out, "ticker {ticker}");

    match retrieved {
        Retrieved::UnknownTicker { ticker, source } => {
            let _ = writeln!(out, "unknown to EDGAR, which does not name {ticker}");
            let _ = writeln!(out, "  looked up in {source}");
        }
        Retrieved::NoFilings { company, source } => {
            let _ = writeln!(out, "company {} {}", company.cik(), company.name());
            let _ = writeln!(out, "  named by {}", company.source());
            let _ = writeln!(out, "no filings");
            let _ = writeln!(out, "  published by {source}");
        }
        Retrieved::History(history) => render_history(history, out),
    }
}

fn render_history(history: &History, out: &mut String) {
    let company = history.company();

    let _ = writeln!(out, "company {} {}", company.cik(), company.name());
    let _ = writeln!(out, "  named by {}", company.source());
    let _ = writeln!(out, "filings {}", history.filings().len());
    let _ = writeln!(out, "  published by {}", history.source());

    let mut carried_by = None;
    for filing in history.filings() {
        if carried_by != Some(filing.source()) {
            let _ = writeln!(out, "  from {}", filing.source());
            carried_by = Some(filing.source());
        }
        render_filing(filing, out);
    }
}

/// One line per filing, with no column widened to fit the widest value in the
/// case: a form type longer than the rest would otherwise move every line in
/// the file, and a golden result is read as a diff.
fn render_filing(filing: &Filing, out: &mut String) {
    let _ = writeln!(
        out,
        "    {} {} filed {} period {} doc {}",
        filing.accession(),
        filing.form(),
        filing.filed(),
        filing.period().unwrap_or("none"),
        filing.document(),
    );
}

/// The first line the two disagree on, rather than both files whole. A golden
/// failure is read by someone deciding which of the two is wrong, and that
/// decision is made at the difference.
fn difference(expected: &str, produced: &str) -> String {
    let mut expected = expected.lines();
    let mut produced = produced.lines();
    let mut number = 1;

    loop {
        match (expected.next(), produced.next()) {
            (None, None) => {
                return "every line matches, so the two differ in what follows the last one"
                    .to_owned();
            }
            (e, p) if e == p => number += 1,
            (e, p) => {
                return format!(
                    "line {number}\n      expected: {}\n      produced: {}",
                    show(e),
                    show(p)
                );
            }
        }
    }
}

/// Quoted and escaped, because a difference that is only trailing whitespace is
/// invisible printed bare and is exactly the kind a golden gate catches.
fn show(line: Option<&str>) -> String {
    match line {
        Some(line) => format!("{line:?}"),
        None => "end of file".to_owned(),
    }
}

#[test]
fn every_fixture_produces_its_expected_result() {
    let dir = stage_fixtures();
    let cases = subdirectories(&dir);

    // An empty sweep is not an absence: the baseline is committed, so no case
    // here means the baseline was deleted, and a gate that passes over nothing
    // reads exactly like one that is holding.
    assert!(
        !cases.is_empty(),
        "{}: holds no fixture, so this gate checks nothing",
        dir.display()
    );

    let mut produced = String::new();
    let mut failures = String::new();

    for case in &cases {
        let name = case.file_name().unwrap_or_default().to_string_lossy();
        let ticker = Ticker::new(read(case, TICKER).trim());
        let expected = read(case, EXPECTED);

        // A pace of its own per case, against the machine's clock. Nothing
        // waits: a turn is owed only to the request after it, and these
        // requests reach no source to owe anything to.
        let mut egress = Egress::new(Recorded::of(case), declaration(), Pace::system());

        produced.clear();
        match filing_history(&mut egress, &ticker) {
            Ok(retrieved) => render(&ticker, &retrieved, &mut produced),
            Err(why) => {
                let _ = writeln!(produced, "ticker {ticker}");
                let _ = writeln!(produced, "not retrieved, {why}");
            }
        }

        if produced != expected {
            failures.push_str(&format!(
                "    fixtures/{STAGE}/{name}: {}\n",
                difference(&expected, &produced)
            ));
        }

        for url in egress.transport().unread() {
            failures.push_str(&format!(
                "    fixtures/{STAGE}/{name}: {url} is recorded and the case never asked for it\n"
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "the stage no longer produces what these fixtures expect:\n{failures}"
    );
}
