[[entry]]
form = "tag"
operands = [
  { taxonomy = "us-gaap", tag = "IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest" },
]

[[entry]]
form = "tag"
operands = [
  { taxonomy = "us-gaap", tag = "IncomeLossFromContinuingOperationsBeforeIncomeTaxesMinorityInterestAndIncomeLossFromEquityMethodInvestments" },
]
