[[entry]]
form = "tag"
operands = [
  { taxonomy = "us-gaap", tag = "ShortTermInvestments" },
]

[[entry]]
form = "tag"
operands = [
  { taxonomy = "us-gaap", tag = "MarketableSecuritiesCurrent" },
]

[[entry]]
form = "tag"
operands = [
  { taxonomy = "us-gaap", tag = "AvailableForSaleSecuritiesDebtSecuritiesCurrent" },
]

[[entry]]
form = "tag"
operands = [
  { taxonomy = "us-gaap", tag = "OtherShortTermInvestments" },
]
